image: ubuntu:16.04

build:
  stage: build

  before_script: 
    - apt update
    - apt -y install curl make cmake libboost-filesystem-dev flex bison gcc g++ git gengetopt bzip2
    - git clone https://github.com/google/double-conversion
    - cd double-conversion
    - cmake -D BUILD_SHARED_LIBS=ON .
    - make && make install
    - curl -L https://sourceforge.net/projects/crpcut/files/crpcut/1.9.4/crpcut-1.9.4.tar.bz2/download > crpcut-1.9.4.tar.bz2
    - tar xvf crpcut-1.9.4.tar.bz2
    - cd crpcut-1.9.4
    - cmake -D LIBRARY_OUTPUT_PATH=/usr/local/lib .
    - make && make install

  script:
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make
    
  # artifacts:
  #   paths:
  #     - ztsdb
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ctest && make rtest
