# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu:16.04

build:
  stage: build

  before_script: 
    - apt update && apt -y install make cmake libboost-filesystem-dev flex bison gcc g++ git
    - git clone https://github.com/google/double-conversion
    - cd double-conversion
    - cmake -D BUILD_SHARED_LIBS=ON .
    - make && make install

  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make
    
  # artifacts:
  #   paths:
  #     - ztsdb
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - ctest
