image: ubuntu:16.04

build:
  stage: build

  before_script: 
    - apt update
    - apt -y install make cmake libboost-filesystem-dev flex bison gcc g++ git gengetopt bzip2 libdouble-conversion-dev python-software-properties
    - add-apt-repository ppa:edd/misc
    - apt-get update
    - apt -y install crpcut
  script:
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make CTEST_OUTPUT_ON_FAILURE=1 test && make rtest
    