include ../Makefile.header

SRCS = zts.cpp dname.cpp display.cpp config.cpp ast.cpp array.cpp	\
	misc.cpp timezone/ztime.cpp timezone/zone.cpp			\
	timezone/localtime.cpp valuevar.cpp period.cpp

include ../Makefile.target
