include ../Makefile.header

SRCS = encode.cpp array.cpp ast.cpp valuevar.cpp valuevar_ic.cpp	\
	net_handler.cpp misc.cpp config.cpp dname.cpp parser_ctx.cpp	\
	anf.cpp zts.cpp display.cpp msg_handler.cpp interp_ctx.cpp	\
	interp.cpp conversion_funcs.cpp base_funcs.cpp			\
	base_funcs_array.cpp base_funcs_array_idx.cpp			\
	base_funcs_ic.cpp base_funcs_math.cpp base_funcs_set.cpp	\
	load_builtin.cpp string.cpp csv.cpp unop_binop_funcs.cpp	\
	base_types.cpp timezone/ztime.cpp timezone/ztime_vector.cpp	\
	timezone/zone.cpp timezone/localtime.cpp interp_error.cpp	\
	period.cpp

include ../Makefile.target.parser
