include ../Makefile.header

SRCS = encode.cpp ast.cpp array.cpp parser_ctx.cpp valuevar.cpp		\
	valuevar_ic.cpp config.cpp net_handler.cpp misc.cpp dname.cpp	\
	anf.cpp zts.cpp display.cpp timezone/ztime.cpp			\
	timezone/zone.cpp timezone/localtime.cpp interp_ctx.cpp		\
	interp.cpp base_types.cpp unop_binop_funcs.cpp			\
	conversion_funcs.cpp interp_error.cpp period.cpp


include ../Makefile.target.parser
