include ../Makefile.header

SRCS = dname.cpp display.cpp ast.cpp array.cpp parser_ctx.cpp		\
	misc.cpp timezone/ztime.cpp timezone/zone.cpp			\
	timezone/localtime.cpp config.cpp valuevar.cpp period.cpp


include ../Makefile.target.parser
