include ../Makefile.header

SRCS = array.cpp dname.cpp config.cpp display.cpp ast.cpp csv.cpp	\
       misc.cpp base_types.cpp zts.cpp timezone/ztime.cpp		\
       timezone/ztime_vector.cpp timezone/zone.cpp			\
       timezone/localtime.cpp valuevar.cpp period.cpp parser_ctx.cpp

include ../Makefile.target.parser
