include ../Makefile.header

SRCS = anf.cpp array.cpp ast.cpp parser_ctx.cpp valuevar.cpp		\
	valuevar_ic.cpp net_handler.cpp misc.cpp dname.cpp zts.cpp	\
	interp.cpp interp_ctx.cpp msg_handler.cpp encode.cpp		\
	load_builtin.cpp display.cpp config.cpp base_funcs.cpp		\
	base_funcs_ic.cpp base_funcs_array.cpp				\
	base_funcs_array_idx.cpp base_funcs_math.cpp			\
	base_funcs_roll.cpp base_funcs_set.cpp conversion_funcs.cpp	\
	csv.cpp base_types.cpp unop_binop_funcs.cpp			\
	timezone/ztime.cpp timezone/ztime_vector.cpp			\
	timezone/zone.cpp timezone/localtime.cpp interp_error.cpp	\
	period.cpp


include ../Makefile.target.parser
